### ISSUE TITLE
KeyError: 'sat+megariad,4' with megaraid RAID controller

### ISSUE THREAD

**Issue by ilyinon** [dampersand/pySMART-0.31#3]
Hello, 
I have tried to get DeviceList()  and have got error on all hosts with megaraid controller:
```
Python 2.7.10 (default, Dec  3 2015, 01:46:33) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pySMART import DeviceList
>>> devlist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'devlist' is not defined
>>> DeviceList()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pySMART/device_list.py", line 51, in __init__
    self._initialize()
  File "/usr/local/lib/python2.7/site-packages/pySMART/device_list.py", line 106, in _initialize
    self.devices.append(Device(name))
  File "/usr/local/lib/python2.7/site-packages/pySMART/device.py", line 140, in __init__
    self.update()
  File "/usr/local/lib/python2.7/site-packages/pySMART/device.py", line 432, in update
    smartctl_type[self.interface], self.name), shell=True,
KeyError: 'sat+megaraid,4'

```

Directly it performs successful
`/usr/sbin/smartctl --all /dev/sda -d sat+megaraid,4`

**Comment by ilyinon** [comment]
I'm sorry you have already fixed it.
